package com.edu.peers.cloudant;

public enum EVENT_KEYS
{
     DEVICE_DATA, PHOTO_SIZE, EVENTS_DATA, ENVIRONMENT_PHOTOS, USERPROFILES_PHOTOS, ATTENDANCE_PHOTOS, DOC_STARTED, DOC_ENDED, HELP_METADATA, STATISTICS_METADATA, USER_METADATA, ERROR_METADATA, SECTION_METADATA
};

